name: Laravel Dusk

on:
  push:
    branches: [ 2.0 ]
  pull_request:
    branches: [ 2.0 ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - laravel: '9.*'
            php: '8.0'
          - laravel: '10.*'
            php: '8.1'
          - laravel: '11.*'
            php: '8.2'
          - laravel: '12.*'
            php: '8.3'

    name: Laravel ${{ matrix.laravel }} - PHP ${{ matrix.php }}

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd
          coverage: none

      - uses: actions/checkout@v4

      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '8.0'
          mysql root password: 123456
          mysql database: laravel
          mysql user: root
          mysql password: 123456

      - name: Install Dependencies
        env:
          LARAVEL_VERSION: ${{ matrix.laravel }}
        run: |
          composer create-project --prefer-dist laravel/laravel laravel-tests "$LARAVEL_VERSION"
          sh ./tests/bin/install-dep.sh

      - name: Install Admin
        run: sh ./tests/bin/install-admin.sh

      - name: Install Xvfb
        run: sudo apt-get install -y xvfb

      - name: Start Server
        run: sh ./tests/bin/start.sh

      - name: Run test suite
        run: cd ./laravel-tests && php artisan dusk
